### ISSUE TITLE
AppVeyor upload issues

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/pyutilib-feedstock#4]
See this [build](https://ci.appveyor.com/project/conda-forge/pyutilib-feedstock/branch/master/job/4eomeurw3aga6kbx) for an example. Snippet shown below. Appears those packages are already updated though. 😕

Have retriggered AppVeyor to build on `master` anyways. Basically we are just running into the same issues elsewhere ( https://github.com/conda-forge/status/issues/4 ). Please see upstream issue ( https://github.com/Anaconda-Platform/support/issues/60 ) on this.

```
python ci_support\upload_or_check_non_existence.py .\recipe conda-forge --channel=main
Using Anaconda API: https://api.anaconda.org
Traceback (most recent call last):
  File "ci_support\upload_or_check_non_existence.py", line 124, in <module>
    main()
  File "ci_support\upload_or_check_non_existence.py", line 106, in main
    on_channel = distribution_exists_on_channel(cli, meta, owner, channel)
  File "ci_support\upload_or_check_non_existence.py", line 69, in distribution_exists_on_channel
    binstar_cli.show_channel(owner=owner, channel=channel)['files']]
  File "C:\conda\lib\site-packages\binstar_client\mixins\channels.py", line 29, in show_channel
    self._check_response(res, [200])
  File "C:\conda\lib\site-packages\binstar_client\__init__.py", line 200, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.NotFound: (u'Not Found: Nothing matches the given URI ([GET] https://api.anaconda.org/channels/conda-forge/main -> 404)', 404)
Command exited with code 1
```

**Comment by jakirkham** [comment]
Feel free to close this when it passes, @whart222.

**Comment by whart222** [comment]
I think this is passing, so I'm closing this issue.
